/** Technical report page. */
export const report = {
  title: "Technical Report",
  toolbar: {
    print: "🖨️ Save / Print report",
    home: "🏠 Home",
  },
  intro: {
    lead: "How Debator works under the hood — live from the same code that runs your matches. The prompts below are generated by the ",
    actual1: "actual",
    mid1: " prompt builder, the model roster is the ",
    actual2: "actual",
    mid2: " catalogue, and the prices are the ",
    actual3: "actual",
    tail: " pricing table. Nothing on this page is a screenshot that can go stale.",
  },

  // Sticky section navigation (scrollspy chips).
  nav: {
    aria: "Report sections",
    offer: "Offer",
    control: "Control",
    providers: "Providers",
    roster: "Roster",
    prompts: "Prompts",
    pipeline: "Deep Debate",
    turnDemo: "Turn demo",
    cost: "Costs",
    stack: "Stack",
  },
  copyLink: {
    title: "Copy a direct link to this section",
    copied: "Link copied",
  },

  // 1 · What we offer
  offer: {
    title: "1 · What we offer",
    debate: {
      heading: "🥊 Debate Mode",
      body: "Two AI models argue opposite sides of your topic across 3–7 fixed rounds — openings, rebuttals, closings. You pick the fighters, the tone, the pace and the length.",
    },
    judge: {
      heading: "⚖️ AI Judge",
      body: "An optional third model judges the finished match blind — summary, strongest and weakest arguments, scores per fighter, and a decisive winner. The app picks a neutral judge automatically, or you choose one.",
    },
    deep: {
      heading: "🌐 Deep Debate",
      body: "Every turn is grounded in a live web search. Fighters quote and cite real sources with [n] markers, shown in a collapsible source list. Fixed format: 3 rounds, standard tone, auto length.",
    },
    footer:
      "Per-turn token usage, latency and an honest running cost are always on screen — the arcade look is the interface, cost transparency is the contract.",
  },

  // 2 · Who controls the match (interactive flow diagram)
  control: {
    title: "2 · The app controls the match — never the models",
    hint: "Click a step to read what really happens at that stage.",
    step1: {
      node: "Validate",
      title: "Setup is validated twice",
      body: "The Start button gates on client-side validation; the server re-validates every request independently (topic length, enums, fighter ids, round caps, Deep Debate limits) — a forged request can't buy more than the UI allows.",
    },
    gate: {
      node: "Limits",
      title: "Rate limits & spend caps run before any model is called",
      body: "Every paid route first checks per-IP rate limits and the global and per-IP daily spend caps. Only a request that passes the gate reaches a provider — and if the limit backend is unreachable, the check fails open so the product keeps working.",
    },
    step2: {
      node: "Plan",
      title: "A fixed turn plan is built before anyone speaks",
      body: (rounds: number, fighterTurns: number, judge: boolean) =>
        `The orchestrator expands your config into the complete list of turns up front — who speaks, in which round, with what task. With ${rounds} rounds that is ${fighterTurns} fighter turns${
          judge ? " plus one judge turn" : ""
        }. Models cannot add, skip or reorder turns.`,
    },
    step3: {
      node: "One turn",
      title: "One API call generates exactly one turn",
      bodyPre: "The browser calls ",
      bodyPost:
        " with the session and the next turn id. The server checks it really is the next pending turn, builds the prompts, calls the provider once, computes the cost, and returns a single message. No loops, no agent autonomy.",
    },
    step4: {
      node: "Ground",
      title: "Deep Debate searches before prompting",
      body: "On deep turns the server first runs a web search (Brave) on your topic and injects the numbered results into the prompt as the model's only allowed evidence. Citation markers that don't match a real source are stripped; sources the model never cited aren't claimed.",
    },
    step5: {
      node: "Judge",
      title: "The judge runs once, at the end",
      bodyPre: "When every round is complete, ",
      bodyPost:
        " asks the judge model for strict JSON — summary, strongest/weakest arguments, scores, winner. The app picks the judge (never one of the fighters when on auto).",
    },
  },

  // 3 · Providers
  providers: {
    title: "3 · Providers & where your data goes",
    colBackend: "Backend",
    colUsedFor: "Used for",
    colKey: "Server-side key",
    colNotes: "Notes",
    openaiUsed: "GPT-4o → GPT-5.5 fighters & judges",
    openaiNotes: "Chat Completions API, streaming-capable",
    deepseekUsed: "DeepSeek V4 fighters & judges",
    deepseekNotes: "OpenAI-compatible endpoint",
    openrouterUsed: "Open-weight fighters under their own brands (Qwen, Llama, Kimi, …)",
    openrouterNotes: "$0 token cost; hidden reasoning capped for fast turns",
    braveUsed: "Deep Debate web research (all fighters)",
    braveNotes: "Only the debate topic is sent as the query — never the transcript",
    securityNote:
      "🔒 All keys live only on the server (Vercel env vars). The browser talks exclusively to our own API routes; no key or provider call ever runs client-side. (The prompt templates are deliberately public — you're reading them live in section 5.) A pluggable search registry means the search engine (and its per-query fee) is swappable by configuration, not code.",
  },

  // 4 · Model roster (interactive fighter cards)
  roster: {
    title: "4 · The fighter roster (live catalogue)",
    via: "via",
    filterAll: "All brands",
    sortRating: "Top rated",
    sortCatalog: "Catalogue order",
    count: (n: number) => `${n} fighters`,
    ratingTitle: "Debate rating",
    tapHint: "Click a fighter for full details and its real per-token pricing.",
    detailFamily: "Family",
    detailBackend: "Backend",
    detailMaxOut: "Max output",
    detailStreaming: "Streaming",
    yes: "Yes",
    no: "No",
    detailPricing: "Pricing / 1M tokens",
    detailInput: "in",
    detailCached: "cached",
    detailOutput: "out",
    footerPre:
      "Ratings are our debate-fit score (0–100). The OpenAI list is verified against the live ",
    footerPost: " endpoint; the OpenRouter roster is a snapshot of their catalogue.",
  },

  // 5 · Prompt playground
  playground: {
    title: "5 · The prompts — exactly what we send",
    sticker: "LIVE",
    intro1: "This playground calls the same prompt builder the server uses. Change a knob and watch the prompt change — that diff is ",
    introEm: "precisely",
    intro2: " what your setting does to the model's instructions.",
    knobTopic: "Topic — becomes the “Topic or idea:” line (and the Deep Debate search query)",
    knobToneLocked: "Tone — locked to Serious in Deep Debate",
    knobTone: "Tone — rewrites the “Tone:” instruction line",
    knobCustomTone: "Custom tone (sanitized + capped at 80 chars, wrapped in a guard sentence)",
    knobRoundsLocked: "Rounds — locked to 3 in Deep Debate",
    knobRounds: "Rounds — sets the turn plan length & each round's task",
    roundsLabel: (n: number) => `${n} rounds`,
    knobLengthLocked: "Length — replaced by the fixed Deep template (≈350–600 words, 1500 tokens)",
    knobLength: "Length — sets the “Maximum length:” line + the provider's token cap",
    lengthLabel: (id: string, tokens: number) => `${id} · ${tokens} tok`,
    knobDeep: "Deep Debate — appends the research addendum + injects numbered web sources",
    deepOff: "Off",
    deepOn: "🌐 On",
    timelineLabel:
      "The match timeline — the deterministic turn plan, built before anyone speaks. Click a turn to preview its prompt",
    timelineJudge: "⚖️ Verdict",
    timelineRound: (n: number) => `Round ${n}`,
    copy: "📋 Copy",
    copied: "✓ Copied",
    tokensApprox: (n: number) => `≈ ${n} tokens`,
    systemLabel: (deep: boolean) =>
      `System prompt — debate mode${deep ? " + Deep Debate addendum" : ""}`,
    turnLabel: (round: number, roundLabel: string, model: string, deep: boolean) =>
      `Turn prompt — round ${round} (“${roundLabel}”), ${model}${
        deep ? " — with injected web sources" : ""
      }`,
    note: "In a real match the “Previous messages” section fills with the actual transcript, and on Deep turns the sample sources above are replaced by live Brave results at request time. Fighters request temperature 0.8 where the model accepts a custom temperature; reasoning-style models (GPT-5.x without “-chat”, o-series) ignore it and run at the provider default.",
    hideJudge: "▴ Hide",
    showJudge: "▾ Show",
    judgeToggleTail: " the judge prompt",
    judgeLabel: "Judge prompt — strict JSON contract so every provider parses identically",
  },

  // 6 · Deep Debate pipeline (interactive flow diagram)
  pipeline: {
    title: "6 · Deep Debate, step by step",
    hint: "Click a stage to see what it does.",
    step1: {
      title: "Search",
      body: "The server queries the search engine (Brave) with your topic and normalizes the top results into numbered sources: title, URL, snippet. Engine, result count and per-query fee are configuration, not code.",
    },
    step2: {
      title: "Rank",
      body: "A 20-result pool is re-ranked before the model sees it: academic and institutional sources (journals, .edu/.gov/.ac domains, official statistics) float to the top, community content and encyclopedias (Wikipedia, Reddit, …) sink to the bottom. Topics with no academic coverage gracefully keep the engine's own ranking.",
    },
    step3: {
      title: "Ground",
      bodyPre: "The sources are injected into the turn prompt as the model's evidence base, explicitly marked as ",
      bodyEm: "untrusted data, never instructions",
      bodyPost: ". The model must cite inline as [1], [2] and may not invent sources.",
    },
    step4: {
      title: "Verify",
      body: "After generation the server strips any [n] marker that doesn't map to a real source, then narrows the attached source list to only what the model actually cited — so \"Sources · 4\" on a card always means four genuinely cited pages.",
    },
    step5: {
      title: "Disclose",
      body: "Clicking an inline [n] chip opens a popup with that source's title, domain, quote and a link out. Each card also shows a collapsible source list, and the result page merges every cited source of the match into one de-duplicated list.",
    },
  },

  // 7 · A real turn
  turnDemo: {
    title: "7 · A real Deep Debate turn (rendered by the real component)",
    intro:
      "This is the live message card component with the data of an actual development test turn (GPT-4o Mini, Deep Debate on, 4 of 5 sources cited — note the cost breakdown and the citation chips):",
    cardSubtitle: "The Quick Wit · Pro",
    cardRoundLabel: "Round 1 · Opening Arguments",
    cardContent:
      "Verifying user age on social media platforms is **essential** for protecting minors in an increasingly digital world [1]. Research indicates that while social media is not inherently detrimental, its use can exacerbate challenges to children's mental health and safety online [2].\n\nRegulators across jurisdictions are converging on the same conclusion: self-declared birthdays are not a safeguard [3]. Privacy-preserving verification — estimation on device, tokens from trusted providers — shows the trade-off between safety and anonymity is engineering, not destiny [4].",
  },

  // 8 · Cost model
  cost: {
    title: "8 · Cost model",
    intro:
      "Every message carries its own bill: provider-reported token usage × the per-model price below (estimated from text length only when a provider doesn't report usage — flagged with a ~). Input served from the provider's prompt cache is billed at the discounted ",
    introCached: "cached",
    introTail:
      " rate, so the number is the real bill. Prices live in one configurable table, never in UI code.",
    colModel: "Model",
    colInput: "$ / 1M input",
    colCached: "$ / 1M cached",
    colOutput: "$ / 1M output",
    explorer: {
      filterPlaceholder: "Filter by model or brand…",
      count: (shown: number, total: number) => `${shown} of ${total} models`,
      barNote: "Bars compare output price on a log scale.",
      empty: "No models match that filter.",
      sortHint: "Click a price column to sort by it; click the model column for catalogue order.",
    },
    note1: (input: string, output: string) =>
      `· Every catalog model bills real usage; unlisted models fall back to $${input}/$${output} per 1M.`,
    note2: (search: string) =>
      `· Deep Debate searches run on the app's search engine (per-query fee absorbed by the arena); in hybrid mode OpenRouter native search adds ~$${search}/turn.`,
    note3:
      "· Standard, cached and output rates verified against the providers' official pages and OpenRouter's live model list (July 2026). OpenRouter models list no cached rate (upstream cache billing varies), so their costs err slightly high.",
    note4:
      "· Cache-aware: when the provider reports cache-hit input tokens (a ♻️ on the cost badge), they bill at the cached rate above — so the cost is the real bill, not an over-estimate.",
    note5: (price: string) =>
      `· Optional fighter voices: free browser speech by default; the server engine (OpenAI speech) bills ≈$${price}/1M characters — about 13¢ per fully voiced match — shown as a 🔊 line in the arena HUD and counted against the same daily spend caps.`,
    estimator: {
      title: "🎮 Estimate a match",
      intro:
        "A rough upper-bound estimate computed from the same pricing table — real matches bill the provider-reported usage, which is usually lower.",
      fighterA: "Fighter A",
      fighterB: "Fighter B",
      rounds: "Rounds",
      roundsLocked: "Rounds — locked to 3 in Deep Debate",
      length: "Response length",
      lengthLocked: "Length — fixed Deep template (1500 tokens)",
      deep: "Deep Debate",
      judgeKnob: "AI Judge",
      on: "On",
      off: "Off",
      total: "Estimated match total",
      turnsLine: (n: number) => `${n} fighter turns`,
      judgeLine: (name: string) => `Judge · ${name}`,
      disclaimer:
        "Assumes ~70% of the per-turn token cap is used and the transcript grows each round. Cache discounts make real bills lower still.",
    },
  },

  // 9 · Stack & configuration
  stack: {
    title: "9 · Stack & configuration",
    stackHeading: "Stack",
    stackItems: [
      "· Next.js 15 App Router + TypeScript (strict), deployed on Vercel",
      "· Tailwind CSS theme tokens — one palette drives the whole arcade UI",
      "· Framer Motion micro-animations; WebAudio synth SFX + file overrides",
      "· Layered server code: routes → orchestrator → prompt builder → provider registry → pricing",
      "· Per-turn deadline budget keeps every call inside the platform's 60s limit",
    ],
    configHeading: "Server configuration",
    badgeCore: "core",
    badgeOptional: "optional",
    configBackends: "model backends",
    configBraveSearch: "Deep Debate web search",
    configSearchProvider: "search engine id (default: brave)",
    configSearchCost: "per-query fee shown in the HUD (default 0)",
    configDeepMode: "\"hybrid\" routes OpenRouter fighters to native :online search",
    configSupabase: "sign-in, match history, community hub — the app fully works without it",
    configLimits: "per-IP rate limits + global/per-IP daily spend caps (fail open)",
    configFooter:
      "Scaling levers are environment variables — paid search tiers, alternate engines and search routing need a dashboard change, not a deploy.",
  },

  footer: "Generated from the live codebase · ",
  footerBadge: "Arcade interface, serious intelligence",
};
